### ISSUE TITLE
Authentication via env_var not working in AiiDAlab example

### ISSUE THREAD

**Issue by pablo-de-andres** [materials-marketplace/python-sdk#32] opened 2022-08-23 08:37 UTC
I am using the latest release of the SDK (v0.3.2) in the UC1 app, and the token is not being picked up properly when I use the `get_app` method without explicitly setting the `access_token`. I assume there is some issue with the environment variable.

It does work when manually provided.

**Comment by csadorf** [comment] 2022-08-23 09:17
I tried to reproduce this and the SDK is picking up the access token and also injecting it into the request. I did not observe any difference in providing it manually or having it picked up from the environment variable. However, in both cases, trying to perform a heartbeat operation check on the SimPARTIX app resulted in a 403.

**Comment by csadorf** [comment] 2022-08-24 12:31
Since it appears that the issue was caused by an expired token, I am going to close this.

**Closed by csadorf** 2022-08-24 12:31 UTC
Labels: question
